### ISSUE TITLE
Initial Setup Issues

### ISSUE THREAD

**Issue by BadCo-NZ** [tystuyfzand/gotify-smtp#2]
Hi, I have been testing this with Nextcloud but have been unsuccessful.

My gotify instance is in docker with a bridge network and is exposed on port 8080.

![image](https://user-images.githubusercontent.com/50016048/148014002-5937d323-a70d-40ed-8dbb-498547967701.png)

See below for settings that I tried in Nextcloud.

![image](https://user-images.githubusercontent.com/50016048/148013971-03297059-2c9e-416b-9dca-75926f0304f6.png)

Am I doing something wrong? 

Does gotify need to be on a dedicated IP so I can use that in the server field for Nextcloud?

**Comment by BadCo-NZ** [comment]
Just tried it with a dedicated static IP and came up with a different error.

![image](https://user-images.githubusercontent.com/50016048/148015396-388a5896-0c86-4c24-aca8-9539fe528dcc.png)

**Comment by TheLastProject** [comment]
Try Authentication Method: Plain

That's how I have my Nextcloud configured

**Comment by BadCo-NZ** [comment]
> Try Authentication Method: Plain
> 
> That's how I have my Nextcloud configured

Thanks, I'll give that a try. 

What about the other options? Are you using an FQDMor IP address? No password?

**Comment by BadCo-NZ** [comment]
> Try Authentication Method: Plain
> 
> That's how I have my Nextcloud configured

Yeah that did it, it must have been the only combination I didn't try haha.

So for anyone else:
```
Send mode: SMTP
Encryption: None
From address: doesn't matter
Authentication method: Plain
Server address : Dedicated static IP
Port: 1025
Credentials:
SMTP Username: <gotifyuser>
SMTP Password: leave blank
```

**Comment by BadCo-NZ** [comment]
Actually a better way to do this without the static IP is to expose port 1025 in the docker compose.

Here is my docker-compose.yml for example.
```
version: "3"

services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    environment:
      - GOTIFY_DEFAULTUSER_PASS=password
      - TZ=Pacific/Auckland
    volumes:
      - /var/lib/docker/volumes/gotify_data:/app/data
    ports:
      - 8080:80 # for webui
      - 1025:1025 # for smtp plugin
```
